const template = require("../../public/flyer/flyer-data.example.json");
const { getAdminPrices } = require("./supabaseAdminPriceService");
const PANEL_ROWS = [2, 4, 6, 8, 10, 12, 14, 16, 20, 22, 26];
async function getFlyerData() { const data = JSON.parse(JSON.stringify(template)); const rows = await getAdminPrices(); for (const product of data.products) { const gama = product.title.replace(/^Gama\s+/i, "").trim(); product.rows = PANEL_ROWS.map((panels) => buildPanelRow(panels, gama, rows)); } return data; }
function buildPanelRow(panels, gama, rows) { const batteryKwh = panels <= 2 ? 0 : Math.min(25, Math.max(5, Math.ceil(panels / 4) * 5)); return [String(panels), formatKwp(panels), batteryKwh ? String(batteryKwh) : "--", ...phasePrices(panels, gama, "Monofásico", rows), ...phasePrices(panels, gama, "Trifásico", rows)]; }
function phasePrices(panels, gama, phase, rows) { if ((phase === "Monofásico" && panels > 20) || (phase === "Trifásico" && panels < 4)) return ["--", "--", "--"]; const config = rows.find((row) => row.category.includes("Pain") && row.gama === gama && row.label.startsWith(`${panels} pain`) && row.label.includes(phase)); const batteryKwh = Math.min(25, Math.max(5, Math.ceil(panels / 4) * 5)); const battery = rows.find((row) => row.category === "Bateria" && row.gama === gama && row.label.startsWith(`${batteryKwh} kWh`)); const backup = rows.find((row) => row.category === "Backup" && row.gama === gama && row.label.startsWith(`${panels} pain`) && row.label.includes(phase)); const noExtras = panels === 2 || (phase === "Trifásico" && panels === 4); return [formatPrice(config?.price), noExtras ? "--" : formatPrice(battery?.price), noExtras ? "--" : formatPrice(backup?.price)]; }
function formatKwp(panels) { return String((panels * 0.53).toFixed(1)).replace(".", ","); }
function formatPrice(value) { return Number(value) > 0 ? `${Math.round(Number(value)).toLocaleString("pt-PT")} €` : "--"; }
module.exports = { getFlyerData };
