create table if not exists public.propostas (
  id bigint generated by default as identity primary key,
  cliente_nome text not null,
  cliente_email text,
  cliente_telemovel text,
  cliente_nif text,
  morada text,
  tipo_fase text not null default 'Monofásico',
  gama text not null default 'Base',
  num_paineis integer not null check (num_paineis in (2, 4, 6, 8, 10, 12, 14, 16, 20, 22, 26)),
  potencia_kwp numeric(8, 2) not null check (potencia_kwp > 0),
  bateria_kwh numeric(8, 2) not null default 0 check (bateria_kwh in (0, 5, 10, 15, 20, 25)),
  preco_manual numeric(10, 2) check (preco_manual is null or preco_manual >= 0),
  modo_preco text not null default 'automatico' check (modo_preco in ('automatico', 'manual')),
  estado text not null default 'rascunho' check (estado in ('rascunho', 'enviada', 'aceite', 'arquivada')),
  dados jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_propostas_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists propostas_updated_at on public.propostas;
create trigger propostas_updated_at
before update on public.propostas
for each row execute function public.set_propostas_updated_at();

alter table public.propostas enable row level security;
