create table if not exists public.precos_carregadores (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  secao text not null check (secao in ('monofasico', 'trifasico', 'instalacao', 'portatil')),
  nome text not null,
  equipamento text,
  ligacao text,
  gestao text,
  potencia text,
  preco_sem_iva numeric(10, 2) not null default 0 check (preco_sem_iva >= 0),
  ordem integer not null default 0,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_precos_carregadores_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists precos_carregadores_updated_at on public.precos_carregadores;
create trigger precos_carregadores_updated_at
before update on public.precos_carregadores
for each row execute function public.set_precos_carregadores_updated_at();

alter table public.precos_carregadores enable row level security;

insert into public.precos_carregadores
  (codigo, secao, nome, equipamento, ligacao, gestao, potencia, preco_sem_iva, ordem)
values
  ('MAC-7,4-1PH-CB',     'monofasico', 'MAC-7,4-1PH-CB',     'CABO',   'Cabo - 5 m',    'Standard',    '7,4 kW', 494.19,    10),
  ('MAC-7,4-1PH-SK',     'monofasico', 'MAC-7,4-1PH-SK',     'TOMADA', 'Tomada T2',     'Standard',    '7,4 kW', 473.61,    20),
  ('MAC-7,4-1PH-CB-DLB', 'monofasico', 'MAC-7,4-1PH-CB-DLB', 'CABO',   'Cabo - 5 m',    'DLB',         '7,4 kW', 535.36,    30),
  ('MAC-7,4-1PH-CB-DLBS','monofasico', 'MAC-7,4-1PH-CB-DLBS','CABO',   'Cabo - 5 m',    'DLB + Solar', '7,4 kW', 543.59,    40),
  ('MAC-7,4-1PH-SK-DLB', 'monofasico', 'MAC-7,4-1PH-SK-DLB', 'TOMADA', 'Tomada T2',     'DLB',         '7,4 kW', 514.78,    50),
  ('MAC-7,4-1PH-SK-DLBS','monofasico', 'MAC-7,4-1PH-SK-DLBS','TOMADA', 'Tomada T2',     'DLB + Solar', '7,4 kW', 523.01,    60),
  ('MAC-2x7,4-1PH-SK',   'monofasico', 'MAC-2x7,4-1PH-SK',   'DUPLO',  '2 tomadas T2',  'Standard',    '2 x 7,4', 1043.08,  70),
  ('MAC-22-3PH-CB',      'trifasico',  'MAC-22-3PH-CB',      'CABO',   'Cabo - 5 m',    'Standard',    '4,1-22',  569.66,    80),
  ('MAC-22-3PH-SK',      'trifasico',  'MAC-22-3PH-SK',      'TOMADA', 'Tomada T2',     'Standard',    '4,1-22',  549.08,    90),
  ('MAC-22-3PH-CB-DLB',  'trifasico',  'MAC-22-3PH-CB-DLB',  'CABO',   'Cabo - 5 m',    'DLB',         '4,1-22',  624.55,   100),
  ('MAC-22-3PH-CB-DLBS', 'trifasico',  'MAC-22-3PH-CB-DLBS', 'CABO',   'Cabo - 5 m',    'DLB + Solar', '4,1-22',  632.79,   110),
  ('MAC-22-3PH-SK-DLB',  'trifasico',  'MAC-22-3PH-SK-DLB',  'TOMADA', 'Tomada T2',     'DLB',         '4,1-22',  603.97,   120),
  ('MAC-22-3PH-SK-DLBS', 'trifasico',  'MAC-22-3PH-SK-DLBS', 'TOMADA', 'Tomada T2',     'DLB + Solar', '4,1-22',  612.20,   130),
  ('MAC-2x22-3PH-SK',    'trifasico',  'MAC-2x22-3PH-SK',    'DUPLO',  '2 tomadas T2',  'Standard',    '2 x 22',  1070.53,  140),
  ('INST-1PH',           'instalacao', 'MONOFASICO',         null,     'Posto de carregamento', null, null, 445.81,  150),
  ('INST-1PH-DUPLO',     'instalacao', 'MONOFASICO DUPLO',   null,     'Posto de carregamento', null, null, 563.99,  160),
  ('INST-3PH',           'instalacao', 'TRIFASICO',           null,     'Posto de carregamento', null, null, 558.17,  170),
  ('INST-3PH-DUPLO',     'instalacao', 'TRIFASICO DUPLO',     null,     'Posto de carregamento', null, null, 687.18,  180),
  ('MAC-3,7-1PH-CB',     'portatil',   'MAC-3,7-1PH-CB',     'PORTATIL', 'Schuko / Tipo 2', 'Standard', '3,7 kW', 155.00, 190)
on conflict (codigo) do nothing;
